# Generated by Django 4.2.30 on 2026-08-14 00:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_productimage_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(blank=True, default='', help_text='Aparece na listagem e como meta description.', max_length=300, verbose_name='resumo')),
                ('body', models.TextField(verbose_name='conteudo')),
                ('cover_icon', models.CharField(default='package', max_length=40, verbose_name='icone de capa')),
                ('published', models.BooleanField(default=False, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='codigo')),
                ('percent_off', models.PositiveIntegerField(help_text='De 1 a 100. Aplicado sobre o subtotal, antes do frete.', verbose_name='desconto (%)')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Deixe vazio para uso ilimitado.', null=True, verbose_name='limite de usos')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='vezes usado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text',
            field=models.TextField(blank=True, default='', help_text='Paragrafo exibido no topo da categoria, para busca organica.', verbose_name='texto de SEO'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120, verbose_name='nome')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='nota')),
                ('comment', models.TextField(verbose_name='comentario')),
                ('approved', models.BooleanField(default=False, help_text='So avaliacoes aprovadas aparecem na loja e contam na nota media.', verbose_name='aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'Avaliacao',
                'verbose_name_plural': 'Avaliacoes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.coupon', verbose_name='cupom'),
        ),
    ]
