# Generated by Django 4.2.30 on 2026-08-14 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost_coupon_category_seo_text_order_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=16, unique=True, verbose_name='codigo')),
                ('owner_name', models.CharField(max_length=200, verbose_name='nome de quem indica')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='e-mail de quem indica')),
                ('reward_threshold', models.PositiveIntegerField(default=3, verbose_name='indicacoes para ganhar recompensa')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='vezes usado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Codigo de indicacao',
                'verbose_name_plural': 'Codigos de indicacao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('cep_start', models.CharField(max_length=8, verbose_name='cep inicial')),
                ('cep_end', models.CharField(max_length=8, verbose_name='cep final')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preco')),
                ('days_min', models.PositiveIntegerField(verbose_name='prazo minimo (dias)')),
                ('days_max', models.PositiveIntegerField(verbose_name='prazo maximo (dias)')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Zona de frete',
                'verbose_name_plural': 'Zonas de frete',
                'ordering': ['cep_start'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='', max_length=60, verbose_name='cor')),
                ('size', models.CharField(blank=True, default='', max_length=60, verbose_name='tamanho')),
                ('sku', models.CharField(blank=True, default='', max_length=40, verbose_name='codigo')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='estoque')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['color', 'size'],
            },
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_variant_per_product'),
        ),
    ]
