# Generated by Django 4.2.30 on 2026-08-14 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_referralcode_shippingzone_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percent_off',
            field=models.PositiveIntegerField(help_text='De 1 a 100. Aplicado sobre o subtotal, antes do frete.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='desconto (%)'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='cep_end',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Use 8 digitos, sem hifen.')], verbose_name='cep final'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='cep_start',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Use 8 digitos, sem hifen.')], verbose_name='cep inicial'),
        ),
    ]
