# Generated by Django 4.2.30 on 2026-08-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_coupon_percent_off_alter_shippingzone_cep_end_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'category'], name='core_produc_active_dab472_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'is_inclusive'], name='core_produc_active_4be8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', '-created_at'], name='core_produc_active_f2d14b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured'], name='core_produc_feature_9698fb_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'approved'], name='core_produc_product_bf3786_idx'),
        ),
    ]
