# Generated by Django 4.2.30 on 2026-08-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_core_produc_active_dab472_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga4_measurement_id', models.CharField(blank=True, default='', max_length=32, verbose_name='GA4 Measurement ID')),
                ('meta_pixel_id', models.CharField(blank=True, default='', max_length=32, verbose_name='Meta Pixel ID')),
                ('whatsapp_cloud_api_token', models.CharField(blank=True, default='', max_length=512, verbose_name='WhatsApp Cloud API Token')),
                ('whatsapp_cloud_phone_id', models.CharField(blank=True, default='', max_length=64, verbose_name='WhatsApp Cloud Phone ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Configuracoes do site',
                'verbose_name_plural': 'Configuracoes do site',
            },
        ),
    ]
